#!/bin/bash
dnf update -y
dnf upgrade -y
dnf install --allowerasing -y jq curl wget unzip vim mariadb105 amazon-cloudwatch-agent

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

echo "Port 2026" >> /etc/ssh/sshd_config
systemctl restart sshd

timedatectl set-timezone Asia/Seoul
touch /var/log/login.log
chmod 644 /var/log/login.log
chown ec2-user:ec2-user /var/log/login.log

cat <<\EOF> /etc/profile.d/login.sh
#!/bin/bash
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
USER_NAME=$(whoami)

echo "$TIMESTAMP - $USER_NAME accessed this server" >> /var/log/login.log
EOF

chmod +x /etc/profile.d/login.sh

cat << EOF > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
{
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/log/login.log",
            "log_group_name": "skills/ec2/login",
            "log_stream_name": "skills_ec2_{instance_id}",
            "retention_in_days": 7
          }
        ]
      }
    }
  }
}
EOF

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json