#!/bin/bash
dnf update -y
sed -i 's/#Port 22/Port 2026/' /etc/ssh/sshd_config
systemctl restart sshd
dnf install -y mariadb105
dnf install -y python3-pip
pip3 install flask
pip3 install pymysql flask
mkdir -p /home/ec2-user/app/
rm -rf /var/log/app/app.log
mkdir -p /var/log/app
chown -R ec2-user:ec2-user /var/log/app
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
unzip /tmp/awscliv2.zip -d /tmp
/tmp/aws/install
rm -rf /tmp/aws /tmp/awscliv2.zip
dnf install --allowerasing -y jq curl wget unzip
cat << 'EOF' > /home/ec2-user/app.py
from flask import Flask, jsonify, request, abort
import pymysql
import logging
import os

app = Flask(__name__)

MYSQL_USER = os.environ.get('MYSQL_USER') 
MYSQL_PASSWORD = os.environ.get('MYSQL_PASSWORD')
MYSQL_HOST = os.environ.get('MYSQL_HOST')
MYSQL_PORT = int(os.environ.get('MYSQL_PORT'))
MYSQL_DBNAME = os.environ.get('MYSQL_DBNAME')

def get_db_connection():
    conn = pymysql.connect(
        host=MYSQL_HOST,
        user=MYSQL_USER,
        password=MYSQL_PASSWORD,
        port=MYSQL_PORT,
        database=MYSQL_DBNAME,
        charset='utf8'
    )
    return conn

def setting_db(message, params=None, fetch=False):
    conn = get_db_connection()
    cursor = conn.cursor()
    if params:
        cursor.execute(message, params)
    else:
        cursor.execute(message)
    
    if fetch:
        result = cursor.fetchall()
        cursor.close()
        conn.close()
        return result
    else:
        conn.commit()
        cursor.close()
        conn.close()

@app.route('/v1/user', methods=['POST'])
def add_user():
    try:
        data = request.json
        name = data.get("name")
        age = data.get("age")
        country = data.get("country")

        message = f"INSERT INTO {MYSQL_DBNAME}.users (name, age, country) VALUES (%s, %s, %s)"
        setting_db(message, params=(name, age, country))
        
        return jsonify({"msg": "User added successfully"}), 200
    except Exception as e:
        logging.error(f"Error occurred: {e}")
        abort(500)

@app.route('/v1/user', methods=['GET'])
def users():
    try:
        name = request.args.get('name')
        if name:
            message = f"SELECT * FROM {MYSQL_DBNAME}.users WHERE name = %s"
            users_data = setting_db(message, params=(name,), fetch=True)

            if users_data:
                body = [{"name": user[0], "age": user[1], "country": user[2]} for user in users_data]
                return jsonify(body), 200
            else:
                return jsonify({"msg": "Name Not Found"}), 404
        else:
            return jsonify({"msg": "Name parameter is required"}), 400

    except Exception as e:
        logging.error(f"Error occurred: {e}")
        abort(500)

@app.route('/healthcheck', methods=['GET'])
def get_healthcheck():
    try:
        ret = {'status': 'ok'}

        return jsonify(ret), 200
    except Exception as e:
        logging.error(e)
        abort(500)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000, debug=True)
EOF
export MYSQL_USER="app-user"
export MYSQL_PASSWORD="zjawjd123"
export MYSQL_HOST="skills-db-rds.cvkc6u22kl99.ap-northeast-2.rds.amazonaws.com"
export MYSQL_PORT="3306"
export MYSQL_DBNAME="skills"
python3 /home/ec2-user/app.py >> /var/log/app/app.log 2>&1 &