#!/bin/bash
dnf update -y
dnf upgrade -y
dnf install --allowerasing -y jq curl wget unzip vim mariadb105 amazon-cloudwatch-agent

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

echo "Port 2026" >> /etc/ssh/sshd_config
systemctl restart sshd

timedatectl set-timezone Asia/Seoul
touch /var/log/login.log
chmod 644 /var/log/login.log
chown ec2-user:ec2-user /var/log/login.log

cat <<\EOF> /etc/profile.d/login.sh
#!/bin/bash
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
USER_NAME=$(whoami)

echo "$TIMESTAMP - $USER_NAME accessed this server" >> /var/log/login.log
EOF

chmod +x /etc/profile.d/login.sh

cat << EOF > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
{
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/log/login.log",
            "log_group_name": "skills/ec2/login",
            "log_stream_name": "skills_ec2_{instance_id}",
            "retention_in_days": 7
          }
        ]
      }
    }
  }
}
EOF

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json



- user data
    
    ```bash
    #!/bin/bash
    dnf update -y
    dnf upgrade -y
    dnf install --allowerasing -y jq curl wget unzip vim mariadb105 amazon-cloudwatch-agent
    
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    
    echo "Port 2026" >> /etc/ssh/sshd_config
    systemctl restart sshd
    
    timedatectl set-timezone Asia/Seoul
    touch /var/log/login.log
    chmod 644 /var/log/login.log
    chown ec2-user:ec2-user /var/log/login.log
    
    cat <<\EOF> /etc/profile.d/login.sh
    #!/bin/bash
    TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
    USER_NAME=$(whoami)
    
    echo "$TIMESTAMP - $USER_NAME accessed this server" >> /var/log/login.log
    EOF
    
    chmod +x /etc/profile.d/login.sh
    
    cat << EOF > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    {
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/login.log",
                "log_group_name": "skills/ec2/login",
                "log_stream_name": "skills_ec2_{instance_id}",
                "retention_in_days": 7
              }
            ]
          }
        }
      }
    }
    EOF
    
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    ```
    

dnf install --allowerasing -y jq curl wget unzip vim mariadb105 amazon-cloudwatch-agent
다운로드 할 때 충돌이 나서 설치가 멈추기 않게 --allowerasing  이 명령어를 쓴다

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
aws cli v2 설치 명령어

unzip awscliv2.zip
awscliv2.zip이라는 이름의 압축 파일을 현재 디렉토리에 압축을 해제하는 명령어

sudo ./aws/install 
다운로드한 aws cli v2 설치 파일을 시스템 전체에 설치하는 명령어

sed -i 's/#Port 22/Port 2026/' /etc/ssh/sshd_config
포트 번호를 22에서 2026으로 바꾸는 명령어

timedatectl set-timezone Asia/Seoul
리눅스 시스템의 시간대를 한국시간으로 바꾸는 명령어

touch /var/log/login.log
/var/log 디렉토리 안에 login.log라는 이름의 빈 파일을 생성하거나 이미 파일이 존재한다면 해당 파일의 최종 수정시간을 현재 시간으로 바꾸는 명령어

chmod 644 /var/log/login.log
 /var/log/login.log 파일의 접근 권한을 644로 바꾸는 명령어 644는 읽기만 가능하다

chown ec2-user:ec2-user /var/log/login.log
 /var/log/login.log 소유자를 ec2-user로 바꾸는 명령어

CAT <</EOF> /etc/profile.d/login.sh
#!/bin/bash
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
USER_NAME=$(whoami)
`TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")`이명령어는 시스템의 날짜와 시간을 출력한다
`**USER_NAME=$(whoami)**`:이 명령어는 령어는 현재 쉘을 실행 중인 사용자의 이다

echo "$TIMESTAMP - $USER_NAME accessed this server" >> /var/log/login.log
EOF
이 명령어는 특정 사용자가 서버에 접속할 때마다 누가 언제 접속했는지 기록을 남기는 로그 작성 코드이다

chmod +x /etc/profile.d/login.sh
/etc/profile.d/디렉토리에 있는 login.sh 파일에 실행 권한을 부여하는 명령어이다

cat << EOF > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
cloudwatch agent 설정 파일을 지정된 경로에 생성하는 쉘 명령어이다

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
설치와 보안 설정을 한번에 끝내는 자동 세팅 스크립트 명령어이다

nohup sh -c "python3 /home/ec2-user/main.pyc 2>&1 | grep --line-buffered -Ev 'healthcheck'" > /home/ec2-user/main.log &
헬스체크 로그만 빼고 실시간으로 기록하며 백그라운드에서 계속 실행해라는 명령어